### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cxbiao** [wenmingvs/NotifyUtil#2]
```
 public static boolean getRunningTask(Context context, String packageName) {
        ActivityManager am = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        ComponentName cn = am.getRunningTasks(1).get(0).topActivity;
        return !TextUtils.isEmpty(packageName) && packageName.equals(context.getPackageName());
    }
```
这个有问题，
应该是
return !TextUtils.isEmpty(packageName) && packageName.equals(cn.getPackageName());

而且我实测5.0以上也是可以的，
需要添加权限
 <uses-permission android:name="android.permission.GET_TASKS" />

**Comment by wenmingvs** [comment]
你好，这个Demo我已经废弃了，如何判断App是否处于后台的相关Demo在这里哦，https://github.com/wenmingvs/AndroidProcess，您看看还有没有问题？

**Comment by cxbiao** [comment]
这个方法还是和新demo一样的，
 ComponentName cn = am.getRunningTasks(1).get(0).topActivity;
        return !TextUtils.isEmpty(packageName) && packageName.equals(cn.getPackageName());
应该是用cn的包名去判断

**Comment by wenmingvs** [comment]
感谢，你的说法是正确的。我按照你的建议修改了，getRunningTask还是仍然可以用的，但是只能判断自己的App是否位于前台，而无法判断其他应用是否位于前台
