### ISSUE TITLE
支持版本

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [wenmingvs/NotifyUtil#3]
好多特性只支持5.0+的设备吧，T1的4.4版本所有效果都一样

**Comment by wenmingvs** [comment]
不知道你说的特性指的是什么？除了最后一种效果是Anroid5.0 特有的，其他都是兼容到4.0以上的。有一些国产Rom会定制他们自己的通知，可能我的一些通知特性就无法正常显示了，比如红米note，这也是我很无奈的地方



wenmingvs@gmail.com
 
发件人： ZhaoKaiQiang
发送时间： 2016-01-26 18:01
收件人： wenmingvs/NotifyUtil
主题： [NotifyUtil] 支持版本 (#3)
好多特性只支持50+的设备吧，T1的44版本所有效果都一样

**Comment by ZhaoKaiQiang** [comment]
应该是ROM问题，图片、按钮、多行等特性在部分国产ROM都不能很好的支持
